src/Entity/Program.php
<?php

namespace App\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\ProgramRepository;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\Common\Collections\ArrayCollection;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use DateTime;
use DateTimeInterface;

#[UniqueEntity('title', message: 'Ce titre existe déjà')]
#[ORM\Entity(repositoryClass: ProgramRepository::class)]
class Program
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(name: 'title', type: 'string', length: 255, unique: true)]
    #[Assert\Regex(pattern: '/plus belle la vie/i', match: false, message: 'On parle de vraies séries ici')]
    #[Assert\NotBlank(message: 'Merci de saisir un titre')]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank]
    private ?string $synopsis = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $poster = null;

    #[ORM\ManyToOne(inversedBy: 'programs')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $Category = null;

    #[ORM\OneToMany(mappedBy: 'Program', targetEntity: Season::class)]
    private Collection $seasons;

    #[ORM\Column(length: 255)]
    private ?string $country = null;

    #[ORM\Column]
    private ?int $year = null;

    #[ORM\ManyToMany(targetEntity: Actor::class, mappedBy: 'Program')]
    private Collection $actors;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    public function __construct()
    {
        $this->seasons = new ArrayCollection();
        $this->actors = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getSynopsis(): ?string
    {
        return $this->synopsis;
    }

    public function setSynopsis(string $synopsis): static
    {
        $this->synopsis = $synopsis;

        return $this;
    }

    public function getPoster(): ?string
    {
        return $this->poster;
    }

    public function setPoster(string $poster): static
    {
        $this->poster = $poster;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->Category;
    }

    public function setCategory(?Category $Category): static
    {
        $this->Category = $Category;

        return $this;
    }

    /**
     * @return Collection<int, Season>
     */
    public function getSeasons(): Collection
    {
        return $this->seasons;
    }

    public function addSeason(Season $season): static
    {
        if (!$this->seasons->contains($season)) {
            $this->seasons->add($season);
            $season->setProgram($this);
        }

        return $this;
    }

    public function removeSeason(Season $season): static
    {
        if ($this->seasons->removeElement($season)) {
            // set the owning side to null (unless already changed)
            if ($season->getProgram() === $this) {
                $season->setProgram(null);
            }
        }

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): static
    {
        $this->country = $country;

        return $this;
    }

    public function getYear(): ?int
    {
        return $this->year;
    }

    public function setYear(int $year): static
    {
        $this->year = $year;

        return $this;
    }

    /**
     * @return Collection<int, Actor>
     */
    public function getActors(): Collection
    {
        return $this->actors;
    }

    public function addActor(Actor $actor): static
    {
        if (!$this->actors->contains($actor)) {
            $this->actors->add($actor);
            $actor->addProgram($this);
        }

        return $this;
    }

    public function removeActor(Actor $actor): static
    {
        if ($this->actors->removeElement($actor)) {
            $actor->removeProgram($this);
        }

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }
}

src/Form/ProgramType.php
<?php

namespace App\Form;

use App\Entity\Actor;
use App\Entity\Program;
use App\Entity\Category;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProgramType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('synopsis')
            ->add('poster')
            ->add('country')
            ->add('year')
            ->add('actors', EntityType::class, [
                'class' => Actor::class,
                'choice_label' => 'firstname',
                'multiple' => true,
                'expanded' => true,
            ])
            ->add('Category', EntityType::class, [
                'class' => Category::class,
                'choice_label' => 'name',
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Program::class,
        ]);
    }
}

src/Controller/ProgramController.php
<?php

namespace App\Controller;

use App\Entity\Season;
use App\Entity\Episode;
use App\Entity\Program;
use App\Form\ProgramType;
use App\Service\ProgramDuration;
use Symfony\Component\Mime\Email;
use App\Repository\ProgramRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bridge\Doctrine\Attribute\MapEntity;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/program', name: 'program_')]
class ProgramController extends AbstractController
{
    #[Route('/', name: 'index')]
    public function index(ProgramRepository $programRepository): Response
    {
        $programs = $programRepository->findAll();

        return $this->render('program/index.html.twig', [
            'website' => 'Wild Series',
            'programs' => $programs,
        ]);
    }

    #[Route('/new', name: 'new')]
    public function new(Request $request, MailerInterface $mailer,  EntityManagerInterface $entityManager, SluggerInterface $slugger): Response
    {
        $program = new Program();
        $form = $this->createForm(ProgramType::class, $program);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $slug = $slugger->slug($program->getTitle());
            $program->setSlug($slug);
            $entityManager->persist($program);
            $entityManager->flush();
            $this->addFlash('success', 'The new program has been created');

            $email = (new Email())
                ->from($this->getParameter('mailer_from'))
                ->to('your_email@example.com')
                ->subject('Une nouvelle série vient d\'être publiée !')
                ->html($this->renderView('Program/newProgramEmail.html.twig', ['program' => $program]));

            $mailer->send($email);

            // Redirect to categories list
            return $this->redirectToRoute('program_index');
        }

        return $this->render('program/new.html.twig', [
            'form' => $form,
        ]);
    }

    #[Route('/{slug}', methods: ['GET'], name: 'show')]
    public function show(Program $program, ProgramDuration $programDuration): Response
    {
        return $this->render('program/show.html.twig', [
            'program' => $program,
            'duration' => $programDuration->Calculate($program),
        ]);
    }

    #[Route('/{program}/seasons/{season}', methods: ['GET'], name: 'season_show')]
    public function showSeason(Program $program, Season $season): Response
    {
        return $this->render('program/season_show.html.twig', [
            'program' => $program,
            'season' => $season,
            'episodes' => $season->getEpisodes(),
        ]);
    }

    #[Route('/{programSlug}/seasons/{season}/episodes/{episodeSlug}', name: 'episode_show')]
    public function showEpisode(
        #[MapEntity(mapping: ['programSlug' => 'slug'])] Program $program,
        #[MapEntity(mapping: ['season' => 'id'])] Season $season,
        #[MapEntity(mapping: ['episodeSlug' => 'slug'])] Episode $episode
    ): Response {

        return $this->render('program/episode_show.html.twig', [
            'program' => $program,
            'seasons' => $season,
            'episodes' => $episode,
        ]);
    }

    #[Route('/{slug}/edit', requirements: ['id' => '\d+'], methods: ['GET', 'POST'], name: 'edit')]
    public function edit(Request $request, Program $program, EntityManagerInterface $entityManager, SluggerInterface $slugger): Response
    {
        $form = $this->createForm(ProgramType::class, $program);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $slug = $slugger->slug($program->getTitle());
            $program->setSlug($slug);
            $entityManager->flush();
            $this->addFlash('success', 'The program has been updated');

            // Redirect to categories list
            return $this->redirectToRoute('program_index');
        }

        return $this->render('program/edit.html.twig', [
            'form' => $form,
            'program' => $program,
        ]);
    }

    #[Route('/{slug}', name: 'delete', methods: ['POST'])]
    public function delete(Request $request, Program $program, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $program->getId(), $request->request->get('_token'))) {
            $entityManager->remove($program);
            $entityManager->flush();
            $this->addFlash('danger', 'The program has been deleted');
        }

        return $this->redirectToRoute('program_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/program/_delete_form.html.twig
<form method="post" action="{{ path('program_delete', {'slug': program.slug}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ program.slug) }}">
    <button class="btn">Delete</button>
</form>

templates/program/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/program/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Program{% endblock %}

{% block body %}
    <h1>Edit program</h1>

    {{ include('program/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('program_index') }}">back to list</a>

    {{ include('program/_delete_form.html.twig') }}
{% endblock %}

templates/program/episode_show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Série #{{ program.id }}
{% endblock %}

{% block body %}
	<h1>Episode #{{ episodes.id }} serie : {{program.title}}</h1>
		{#<img src="{{ vich_uploader_asset(program) }}" alt="{{ program.title }}">#}
		</div>
			<h2>titre de l'episode :{{ episodes.title }}</h2>
			<p>saison :{{ seasons.number }}</p>
			<p>resumer :{{ episodes.synopsis }}</p>	
{% endblock %}

templates/program/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}All programs
{% endblock %}

{% block body %}
	<h1>Toutes les séries de la table program :
	</h1>
	<a href="{{ path('program_new')}}">Ajouter un program</a>
	{% for program in programs %}
		<div>
			<h2>{{ loop.index }}
				/
				{{ program.title }}
				- Catégorie :
				{{ program.category.name }}</h2>
			<p>{{ program.synopsis }}</p>
			<a href="{{ path("program_show", { slug: program.slug }) }}">Voir la fiche</a>
			<a href="{{ path("program_edit", { slug: program.slug }) }}">Modifier la fiche</a>
		</div>
	{% else %}
		Aucune série trouvée.
	{% endfor %}

	<a href="{{ path('app_index') }}">
		Retour à l'accueil
	</a>
{% endblock %}

templates/program/new.html.twig
{% extends "base.html.twig" %}

{% block body %}
    {{ form_start(form) }}
    {{ form_widget(form) }}
    <button type="submit">Add program</button>
    {{ form_end(form) }}
{% endblock %}

templates/program/season_show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Série #{{ program.id }}
{% endblock %}

{% block body %}
	<h1>Saison {{ season.number }} de {{ program.title }}</h1>
	{{ season.description }}
	<ul>
		{% for episode in episodes %}
			<li>
			<a href="{{ path('program_episode_show', {programSlug: program.slug, season: season.id, episodeSlug: episode.slug}) }}">
					Episode {{ episode.number }} : {{ episode.title }}
				</a>
			</li>
		{% endfor %}
	</ul>
{% endblock %}

templates/program/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Série #{{ program.id }}
{% endblock %}

{% block body %}
	<div class="media">
		<img class="align-self-start mr-3" src="{{program.poster}}" alt="{{ program.title }} poster">
		<div class="media-body">
			<h1 class="mt-0">{{ program.title }}</h1>
			<p>{{ program.synopsis }}</p>
			<p>Catégorie :
				{{ program.category.name }}</p>
			<p>Durée : {{duration}}</p>
		</div>
	</div>
	<h2>Les saisons</h2>
	<ul>
		{% for season in program.seasons %}
					<li>
						<a href="{{ path('program_season_show', {'program': program.id, 'season': season.id}) }}">
							Saison :{{ season.number }}
						</a>
					</li>
		{% endfor %}
	</ul>
	<strong>Acteurs :</strong>
	<ul>
		{% for actor in program.actors %}
			<li><a href=" {{path('actor_show', {id: actor.id})}}">{{ actor.firstname }},
				{{actor.lastname}}</a></li>
		{% else %}
			<li>Aucun acteur pour cette série</li>
		{% endfor %}
	</ul>
	<a href="{{ path('program_index') }}">
		Retour à la liste des programmes
	</a>

{% endblock %}